name: "pu'reh"
favicon: null
layout_spectrum: 0.25201
typography_spectrum: 0.1391
title: "pu'reh"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8aa3cf'
    - '#e0c6c3'
    - '#937985'
    - '#6f5b63'
  brandStrength: 0.25
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
